apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-monitor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: service-monitor
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: service-monitor
subjects:
- kind: ServiceAccount
  name: service-monitor
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: service-monitor
  apiGroup: rbac.authorization.k8s.io
