apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jitsi-meet.jicofo.fullname" . }}-defaults
  labels:
    {{- include "jitsi-meet.jicofo.labels" . | nindent 4 }}
data:
  jicofo.conf: |
    {{- if .Values.jicofo.custom.defaults._jicofo_conf }}
      {{- .Values.jicofo.custom.defaults._jicofo_conf | nindent 4 }}
    {{- else }}
    # Using jicofo /default/jicofo.conf from container image
    {{ end }}
  logging.properties: |
    {{- if .Values.jicofo.custom.defaults._logging_properties }}
      {{- .Values.jicofo.custom.defaults._logging_properties | nindent 4 }}
    {{- else }}
    # Using jicofo /default/logging.properties from container image
    {{ end }}
