
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  NOTION_USERNAME: "{{ .Values.notion.username }}"
  IMAP_USERNAME: "{{ .Values.imap.username }}"
  S3_HOST: "{{ .Values.s3.host }}"
  S3_BUCKET: "{{ .Values.s3.bucket }}"
  HEALTHCHECK_URL: "{{ .Values.healthcheckUrl }}"
  CACHE_PATH: "/data/credentials"
  TMP_DIR: "/data/working"
  GPG_PUBKEY_FILE: "/var/keys/pubkey.asc"
  WEBDRIVER_URL: "http://{{ .Release.Name}}-selenium-webdriver:4444"
  WORKSPACES: "{{ .Values.workspaces }}"
