apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-notion-download
spec:
  schedule: "{{ .Values.backupSchedule }}"
  timeZone: 'Etc/UTC'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      timezone: "Etc/UTC"
      template:
        metadata:
          labels:
            app: {{ .Release.Name }}
        spec:
          restartPolicy: Never
          containers:
            - name: notion-backup
              image: ghcr.io/ethdevops/notion-backup-tool:{{ .Values.imageTag }}
              volumeMounts:
                - name: credential-cache
                  mountPath: /data/credentials
                - name: working-dir
                  mountPath: /data/working
                - name: pgp-key-vol
                  mountPath: /var/keys
                  readOnly: true
              env:
                - name: MODE
                  value: "download"

              envFrom:
                - configMapRef:
                    name: {{ .Release.Name }}-config
                - secretRef:
                    name: {{ .Release.Name }}-secret
          nodeSelector:
            kubernetes.io/os: linux
          volumes:
            - name: credential-cache
              persistentVolumeClaim: 
                claimName: {{ .Release.Name }}-cred-cache
            - name: working-dir
              persistentVolumeClaim: 
                claimName: {{ .Release.Name }}-working
            - name: pgp-key-vol
              secret:
                secretName: {{ .Release.Name }}-pgp-key
