apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-notion-trigger
spec:
  schedule: "{{ .Values.triggerSchedule }}"
  timeZone: 'Etc/UTC'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ .Release.Name }}
        spec:
          restartPolicy: Never
          containers:
            - name: notion-backup
              image: docker.ethquokkaops.io/ethquokkaops/ethdevops/notion-backup-tool:{{ .Values.imageTag }}
              volumeMounts:
                - name: credential-cache
                  mountPath: /data/credentials
                - name: working-dir
                  mountPath: /data/working
                - name: pgp-key-vol
                  mountPath: /var/keys
                  readOnly: true
              env:
                - name: MODE
                  value: "trigger"

              envFrom:
                - configMapRef:
                    name: {{ .Release.Name }}-config
                - secretRef:
                    name: {{ .Release.Name }}-secret
          nodeSelector:
            kubernetes.io/os: linux
          volumes:
            - name: credential-cache
              persistentVolumeClaim: 
                claimName: {{ .Release.Name }}-cred-cache
            - name: working-dir
              persistentVolumeClaim: 
                claimName: {{ .Release.Name }}-working
            - name: pgp-key-vol
              secret:
                secretName: {{ .Release.Name }}-pgp-key
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-cred-cache
annotations:
  "helm.sh/hook": post-install,post-upgrade
  "helm.sh/hook-delete-policy": before-hook-creation
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-working
annotations:
  "helm.sh/hook": post-install,post-upgrade
  "helm.sh/hook-delete-policy": before-hook-creation
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 15Gi
