apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
stringData:
  S3_ACCESS_KEY: "{{ .Values.s3.accessKey }}"
  S3_SECRET_KEY: "{{ .Values.s3.secretKey }}"
  NOTION_PASSWORD: "{{ .Values.notion.password }}"
  IMAP_PASSWORD: "{{ .Values.imap.password }}"
