apiVersion: v1
data:
{{- range $key, $val := .Values.secretenvs }}
  {{ $key }}: {{ $val | default "mock" | b64enc }}
{{- end }}
{{- range $key, $val := .Values.binsecretenvs }}
  {{ $key }}: {{ $val }}
{{- end }}
kind: Secret
metadata:
  creationTimestamp: null
  name: {{ .Values.custom.confMapName | default "default-sec" }}
type: Opaque

{{- range .Values.extraSecrets }}
---
apiVersion: v1
data:
{{- range $key, $val := .secretenvs }}
  {{ $key }}: {{ $val | default "mock" | b64enc }}
{{- end }}
{{- range $key, $val := .binsecretenvs }}
  {{ $key }}: {{ $val }}
{{- end }}
kind: Secret
metadata:
  creationTimestamp: null
  name: {{ .name }}
type: Opaque
{{- end }}
