{{- $needDbPassword := not .Values.databaseExistingSecret.name }}
{{- $needAdminPassword := and .Values.app.setupAdminPassword (not .Values.app.setupAdminPasswordExistingSecret.name) }}
{{- if or $needDbPassword $needAdminPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-engelsystem
  labels:
    app: {{ .Release.Name }}-engelsystem
type: Opaque
stringData:
  {{- if $needDbPassword }}
  MYSQL_PASSWORD: {{ include "engelsystem.dbPassword" . | quote }}
  {{- end }}
  {{- if $needAdminPassword }}
  SETUP_ADMIN_PASSWORD: {{ .Values.app.setupAdminPassword | quote }}
  {{- end }}
{{- end }}
