apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-engelsystem
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: {{ .Release.Name }}-engelsystem
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    app: {{ .Release.Name }}-engelsystem
