{{- if and .Values.nginx.enabled .Values.nginx.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gnosis-safe.fullname" . }}-nginx-config
  labels:
    {{- include "gnosis-safe.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    
    http {
        upstream web {
            server {{ include "gnosis-safe.fullname" . }}:{{ .Values.service.port }};
        }
        
        server {
            listen 8000;
            location / {
                proxy_pass http://web;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
    }
{{- end }}