apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gnosis-safe.fullname" . }}-secret
  labels:
    {{- include "gnosis-safe.labels" . | nindent 4 }}
type: Opaque
data:
  # Add your secret environment variables here as base64 encoded values
  # Example:
  # SECRET_KEY: {{ "your-secret-key" | b64enc | quote }}