{{- if .Values.staticWeb.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gnosis-safe.fullname" . }}-static-web
  labels:
    {{- include "gnosis-safe.labels" . | nindent 4 }}
    app.kubernetes.io/component: static-web
spec:
  replicas: {{ .Values.staticWeb.replicaCount }}
  selector:
    matchLabels:
      {{- include "gnosis-safe.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: static-web
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gnosis-safe.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: static-web
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gnosis-safe.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: static-web
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.staticWeb.image.repository }}:{{ .Values.staticWeb.image.tag }}"
          imagePullPolicy: {{ .Values.staticWeb.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}