apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "glitchtip.fullname" . }}-web
  labels:
    {{- include "glitchtip.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  {{- if not .Values.web.autoscaling.enabled }}
  replicas: {{ .Values.web.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "glitchtip.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
      annotations:
        {{- if .Values.valkey.enabled }}
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- end }}
        tag: "{{ .Values.image.tag }}"
        {{- if .Values.web.podAnnotations }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.web.podAnnotations "context" $ ) | nindent 8 }}
        {{- end }}
      labels:
        {{- include "glitchtip.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "glitchtip.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
    {{- with .Values.web.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ . }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- if .Values.web.args }}
          args: {{- toYaml .Values.web.args | nindent 10}}
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.web.port | default 8000 }}
              protocol: TCP
          livenessProbe:
            failureThreshold: {{ .Values.web.livenessProbe.failureThreshold }}
            httpGet:
              path: {{ .Values.web.livenessProbe.path | default "/_health/" }}
              port: {{ .Values.web.port | default 8000 }}
            initialDelaySeconds: {{ .Values.web.livenessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.web.livenessProbe.timeoutSeconds }}
          readinessProbe:
            failureThreshold: {{ .Values.web.readinessProbe.failureThreshold }}
            httpGet:
              path: {{ .Values.web.readinessProbe.path | default "/_health/" }}
              port: {{ .Values.web.port | default 8000 }}
            initialDelaySeconds: {{ .Values.web.readinessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.web.readinessProbe.timeoutSeconds }}
          {{- with .Values.web.lifecycle }}
          lifecycle:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            {{- if .Values.web.embedWorker }}
            - name: GLITCHTIP_EMBED_WORKER
              value: "true"
            - name: SKIP_INIT
              value: "true"
            {{- end }}
            {{- include "glitchtip.shared.env" . | nindent 12 }}
            {{- include "glitchtip.database.env" (dict "root" . "component" .Values.web) | nindent 12 }}
            {{- include "glitchtip.valkey.env" . | nindent 12 }}
            {{- with .Values.extraEnvVars }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.web.extraEnvVars }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- if or .Values.extraEnvFrom .Values.web.extraEnvFrom }}
          envFrom:
            {{- with .Values.extraEnvFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.web.extraEnvFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- with .Values.extraVolumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 10 }}
          {{- end }}
      {{- with .Values.web.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.web.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.web.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      {{- with .Values.extraVolumes }}
      volumes:
        {{- toYaml . | nindent 6 }}
      {{- end }}