{{- if .Values.server.storage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-server-storage
  labels:
    {{- include "twentycrm.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.server.storage.storageClassName }}
  storageClassName: {{ .Values.server.storage.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.server.storage.storageSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-docker-data
  labels:
    {{- include "twentycrm.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.server.storage.storageClassName }}
  storageClassName: {{ .Values.server.storage.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.server.storage.dockerDataSize }}
{{- end }}
