{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    {{- include "twentycrm.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "twentycrm.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "twentycrm.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: redis
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - name: redis
        image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
        imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
        command:
        - redis-server
        - --maxmemory-policy
        - {{ .Values.redis.maxmemoryPolicy }}
        - --protected-mode
        - "no"
        ports:
        - name: redis
          containerPort: {{ .Values.redis.port }}
          protocol: TCP
        resources:
          {{- toYaml .Values.redis.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    {{- include "twentycrm.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    {{- include "twentycrm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  ports:
  - name: redis
    port: {{ .Values.redis.port }}
    targetPort: redis
  {{- if .Values.service.sessionAffinity }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ .Values.service.sessionAffinityTimeout }}
  {{- end }}
{{- end }}
