{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-tokens
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "twentycrm.labels" . | nindent 4 }}
type: Opaque
data:
  accessToken: {{ .Values.secrets.accessToken | b64enc | quote }}
  loginToken: {{ .Values.secrets.loginToken | b64enc | quote }}
  refreshToken: {{ .Values.secrets.refreshToken | b64enc | quote }}
{{- end }}
