{{- if and .Values.postgres.enabled (not .Values.postgres.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secret
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "twentycrm.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.postgres.password | b64enc | quote }}
{{- end }}
