apiVersion: v2
name: s3-bucket-sync
description: Keeps 2 s3 buckets in sync
type: application

version: 0.0.3

# App metadata
appVersion: "v0.9.0"
sources:
  - https://github.com/EthDevOps/s3-sync-docker
maintainers:
  - name: elasticroentgen
    email: markus.keil@ethereum.org
