commonAnnotations: {}

baseDomain: pad.example.com
sandboxDomain: sandbox.example.com
admins: []
maxUploadSize: 1
maxPremiumUploadSize: 100
loginSalt: "abcdefg"
installOffice: no
sso:
  existingSecret: "" # Name of the Kubernetes secret containing SSO credentials
  secretKeys:
    client_id: "client_id" # Key in the secret for client ID
    client_secret: "client_secret" # Key in the secret for client secret

podAnnotations: {}
podLabels: {}
extraInitContainers: {}
resources: {}
image:
  repository: docker.ethquokkaops.io/ethquokkaops/ethdevops/cryptpad-docker
  tag: main

service:
  type: ClusterIP
  annotations: {}

ingress:
  enabled: true
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  tls:
    secretName: chart-example-tls
