replicaCount: 1

image:
  repository: docker.ethquokkaops.io/ethquokkaops/ethdevops/safe-transaction-service
  pullPolicy: IfNotPresent
  tag: "main"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8888
  annotations: {}
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Application-specific configuration
config:
  envFile: .env
  runMigrations: true

# External services
nginx:
  enabled: true
  image:
    repository: nginx
    tag: alpine
  service:
    port: 8000
  configMap:
    enabled: true

redis:
  enabled: true
  image:
    repository: redis
    tag: alpine
  service:
    port: 6379
  healthcheck:
    enabled: true

rabbitmq:
  enabled: true
  image:
    repository: rabbitmq
    tag: alpine
  service:
    port: 5672
  healthcheck:
    enabled: true

postgresql:
  enabled: true
  image:
    repository: postgres
    tag: 16-alpine
  auth:
    username: postgres
    password: postgres
    database: postgres
  service:
    port: 5432
  healthcheck:
    enabled: true

# Workers configuration
workers:
  indexer:
    enabled: true
    queues: "default,indexing,processing"
    replicaCount: 1
  
  contractsTokens:
    enabled: true
    queues: "contracts,tokens"
    replicaCount: 1
  
  scheduler:
    enabled: true
    replicaCount: 1

# Flower (Celery monitoring)
flower:
  enabled: false
  service:
    port: 5555

# Persistence
persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 8Gi
