apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prosody.fullname" . }}-defaults
  labels:
    {{- include "prosody.labels" . | nindent 4 }}
data:
  prosody.cfg.lua: |
    {{- if .Values.custom.defaults._prosody_cfg_lua }}
      {{- .Values.custom.defaults._prosody_cfg_lua | nindent 4 }}
    {{- else }}
    # Using prosody /default/prosody.cfg.lua from container image
    {{ end }}
  saslauthd.conf: |
    {{- if .Values.custom.defaults._saslauthd_conf }}
      {{- .Values.custom.defaults._saslauthd_conf | nindent 4 }}
    {{- else }}
    # Using prosody /default/saslauthd.conf from container image
    {{ end }}
{{ (.Files.Glob "files/jitsi-meet.cfg.lua").AsConfig | indent 2}}
