apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prosody.fullname" . }}-cont-inits
  labels:
    {{- include "prosody.labels" . | nindent 4 }}
data:
  10-config: |
    {{- if .Values.custom.contInit._10_config }}
      {{- .Values.custom.contInit._10_config | nindent 4 }}
    {{- else }}
    # Using prosody /etc/cont-init.d/10-config from container image
    {{ end }}
