apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  app-config.toml: |-
    [app]
    address = "0.0.0.0:9000"    
    [db]
    host = "{{ if .Values.postgres.enabled }}{{ .Release.Name }}-postgres{{ else }}{{ .Values.postgres.hostname }}{{ end }}"
    port = 5432
    user = "{{ .Values.postgres.user }}"
    password = "{{ .Values.postgres.password }}"
    database = "{{ .Values.postgres.database }}"
    ssl_mode = "disable"
    max_open = 25
    max_idle = 25
    max_lifetime = "300s"