apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-listmonk
spec:
  selector:
    app: {{ .Release.Name }}-listmonk
  ports:
    - name: http
      port: 80
      targetPort: 9000 