apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-config
type: Opaque
stringData:
  TELEPORT_TOKEN: "{{ .Values.teleport.token }}"
  TELEPORT_DOMAIN: "{{ .Values.teleport.domain }}"
  ARGOCD_DOMAIN: "{{ .Values.argocd.domain }}"
  ARGOCD_USERNAME: "{{ .Values.argocd.username }}"
  ARGOCD_PASSWORD: "{{ .Values.argocd.password }}"
