apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "mattermost-mail2most.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: mail2most
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      app.kubernetes.io/name: {{ include "mattermost-mail2most.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Release.Name }}
        app.kubernetes.io/name: {{ include "mattermost-mail2most.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: mail2most
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
      - name: config-init
        image: busybox:1.36
        command: ['sh', '-c']
        args:
        - |
          echo "Preparing mail2most configuration..."
          cp /tmp/config/mail2most.conf /mail2most/conf/mail2most.conf.tmp
          # Replace placeholders with actual secret values
          sed -i "s|\${IMAP_PASSWORD}|$IMAP_PASSWORD|g" /mail2most/conf/mail2most.conf.tmp
          sed -i "s|\${MATTERMOST_TOKEN}|$MATTERMOST_TOKEN|g" /mail2most/conf/mail2most.conf.tmp
          mv /mail2most/conf/mail2most.conf.tmp /mail2most/conf/mail2most.conf
          echo "Configuration prepared successfully"
        env:
        - name: IMAP_PASSWORD
          valueFrom:
            secretKeyRef:
              {{- if .Values.secrets.imapExistingSecret }}
              name: {{ .Values.secrets.imapExistingSecret }}
              key: {{ .Values.secrets.imapExistingSecretKey }}
              {{- else }}
              name: {{ .Release.Name }}-secret
              key: imap-password
              {{- end }}
        - name: MATTERMOST_TOKEN
          valueFrom:
            secretKeyRef:
              {{- if .Values.secrets.mattermostExistingSecret }}
              name: {{ .Values.secrets.mattermostExistingSecret }}
              key: {{ .Values.secrets.mattermostExistingSecretKey }}
              {{- else }}
              name: {{ .Release.Name }}-secret
              key: mattermost-token
              {{- end }}
        volumeMounts:
        - name: config-template
          mountPath: /tmp/config
          readOnly: true
        - name: config
          mountPath: /mail2most/conf
        securityContext:
          runAsUser: 0
          runAsNonRoot: false
      containers:
      - name: mail2most
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/mail2most/mail2most"]
        args: ["-c", "/mail2most/conf/mail2most.conf"]
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1000
        volumeMounts:
        - name: config
          mountPath: /mail2most/conf
          readOnly: true
        {{- if .Values.persistence.enabled }}
        - name: data
          mountPath: /mail2most/data
          subPath: data
        - name: data
          mountPath: /mail2most/logs
          subPath: logs
        {{- else }}
        - name: data-tmp
          mountPath: /mail2most/data
        - name: logs-tmp
          mountPath: /mail2most/logs
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      volumes:
      - name: config-template
        configMap:
          name: {{ .Release.Name }}-config
      - name: config
        emptyDir: {}
      {{- if .Values.persistence.enabled }}
      - name: data
        persistentVolumeClaim:
          {{- if .Values.persistence.existingClaim }}
          claimName: {{ .Values.persistence.existingClaim }}
          {{- else }}
          claimName: {{ .Release.Name }}-data
          {{- end }}
      {{- else }}
      - name: data-tmp
        emptyDir: {}
      - name: logs-tmp
        emptyDir: {}
      {{- end }}

{{- define "mattermost-mail2most.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{- define "mattermost-mail2most.fullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- if contains $name .Release.Name }}
{{- .Release.Name | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
{{- end }}