{{- if and .Values.webhook.tls.enabled (not .Values.webhook.tls.provided) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "kube-guard.fullname" . }}-ca-bundle
  labels:
    {{- include "kube-guard.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  template:
    metadata:
      name: {{ include "kube-guard.fullname" . }}-ca-bundle
      labels:
        {{- include "kube-guard.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ include "kube-guard.serviceAccountName" . }}
      containers:
      - name: ca-bundle-updater
        image: alpine/k8s:1.28.0
        command:
        - /bin/sh
        - -c
        - |
          set -e

          SECRET_NAME="{{ .Values.webhook.tls.secretName | default (printf "%s-tls" (include "kube-guard.fullname" .)) }}"
          NAMESPACE="{{ .Release.Namespace }}"

          # Get CA bundle from our self-signed certificate (since it's the CA for itself)
          CA_BUNDLE=$(kubectl get secret $SECRET_NAME -n $NAMESPACE -o jsonpath='{.data.tls\.crt}')

          if [ -z "$CA_BUNDLE" ]; then
            echo "Failed to get CA bundle from secret $SECRET_NAME"
            exit 1
          fi

          echo "Updating ValidatingWebhookConfiguration with CA bundle..."
          kubectl patch validatingwebhookconfiguration {{ include "kube-guard.fullname" . }}-validator \
            --type='json' \
            -p='[{"op": "replace", "path": "/webhooks/0/clientConfig/caBundle", "value": "'$CA_BUNDLE'"}]'

          echo "Updating MutatingWebhookConfiguration with CA bundle..."
          kubectl patch mutatingwebhookconfiguration {{ include "kube-guard.fullname" . }}-mutator \
            --type='json' \
            -p='[{"op": "replace", "path": "/webhooks/0/clientConfig/caBundle", "value": "'$CA_BUNDLE'"}]'

          echo "CA bundle updated successfully"

        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
{{- end }}
