{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kube-guard.serviceAccountName" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "kube-guard.labels" . | nindent 4 }}
{{- end }}