{{- if and .Values.mariadb.enabled (not .Values.mariadb.existingSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-bookstack-db
type: Opaque
data:
  DB_PASSWORD: {{ .Values.mariadb.password | b64enc | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.mariadb.rootPassword | b64enc | quote }}
{{- end }}
