apiVersion: v2
name: hotcrp
description: HotCRP - Conference review software (paper submission and reviewing)
type: application

version: 0.1.0

# App metadata
appVersion: "3.3.1"
maintainers:
  - name: elasticroentgen
    email: markus.keil@ethereum.org
