apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-monitor
  labels:
    app: {{ .Release.Name }}-monitor
spec:
  schedule: "{{ .Values.cronJob.schedule }}"
  timeZone: 'Etc/UTC'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ .Release.Name }}-monitor
        spec:
          restartPolicy: OnFailure
          containers:
            - name: jitsi-monitor
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              envFrom:
                - configMapRef:
                    name: {{ .Release.Name }}-config
              volumeMounts:
                - name: screenshots
                  mountPath: /app/screenshots
          volumes:
            - name: screenshots
              emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-monitor
spec:
  selector:
    app: {{ .Release.Name }}-monitor
  ports:
    - name: http
      port: 8000
