apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-monitor
  labels:
    app: {{ .Release.Name }}-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-monitor
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-monitor
      {{- if .Values.podAnnotations }}
      annotations: 
        {{- .Values.podAnnotations | toYaml | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: jitsi-monitor
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: http
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
          volumeMounts:
            - name: screenshots
              mountPath: /app/screenshots
      volumes:
        - name: screenshots
          emptyDir: {}