{{- if .Values.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis.secretName" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
type: Opaque
data:
  redis-password: {{ .Values.auth.password | b64enc | quote }}
{{- end }}