apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-sso
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  client_id: {{ .Values.sso.client_id | b64enc }}
  client_secret: {{ .Values.sso.client_secret | b64enc }}