apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-cryptpad
spec:
  selector:
    app: {{ .Release.Name }}-cryptpad
  ports:
    - name: http
      port: 3000
    - name: websocket
      port: 3003
