apiVersion: v2
name: docmost
description: OpenSource alternative for Notion
type: application

version: 0.1.3

# App metadata
appVersion: "1.0.0"
maintainers:
  - name: elasticroentgen
    email: markus.keil@ethereum.org
dependencies:
- name: postgresql
  version: 16.x.x
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: postgresql.enabled
- name: redis
  version: 18.x.x
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: redis.enabled
