apiVersion: v2
name: docmost
description: OpenSource alternative for Notion
type: application

version: 0.2.0

# App metadata
appVersion: "1.0.0"
maintainers:
  - name: elasticroentgen
    email: markus.keil@ethereum.org
dependencies:
- name: postgresql
  version: 1.1.3
  repository: https://ethdevops.github.io/helm-charts
  condition: postgresql.enabled
- name: redis
  version: 18.x.x
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: redis.enabled
