apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: admin
spec:
  # Secret names are always required.
  secretName: admin-tls

  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048

  duration: 2160h # 90d
  renewBefore: 360h # 15d

  isCA: false

  commonName: admin
  subject:
    organizations:
      - Company
    countries:
      - US
    localities:
      - California

  # Issuer references are always required.
  issuerRef:
    name: ca-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dashboard
spec:
  # Secret names are always required.
  secretName: dashboard-tls

  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048

  duration: 2160h # 90d
  renewBefore: 360h # 15d

  isCA: false

  commonName: dashboard
  subject:
    organizations:
      - Company
    countries:
      - US
    localities:
      - California

  # Issuer references are always required.
  issuerRef:
    name: ca-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: node
spec:
  # Secret names are always required.
  secretName: node-tls

  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048

  duration: 2160h # 90d
  renewBefore: 360h # 15d

  isCA: false

  commonName: indexer
  subject:
    organizations:
      - Company
    countries:
      - US
    localities:
      - California

  # Issuer references are always required.
  issuerRef:
    name: ca-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: filebeat
spec:
  # Secret names are always required.
  secretName: filebeat-tls

  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048

  duration: 2160h # 90d
  renewBefore: 360h # 15d

  isCA: false

  commonName: filebeat
  subject:
    organizations:
      - Company
    countries:
      - US
    localities:
      - California

  # Issuer references are always required.
  issuerRef:
    name: ca-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: Issuer