{{- include "glitchtip.validateValues" . -}}
{{- if .Values.valkey.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "glitchtip.fullname" . }}
  labels:
    {{- include "glitchtip.labels" . | nindent 4 }}
type: Opaque
data:
  REDIS_URL: {{ include "glitchtip.valkey.url" . | b64enc | quote }}
{{- end }}
