apiVersion: v2
name: keycloak
version: 18.10.8
appVersion: "26.1"
description: Open Source Identity and Access Management For Modern Applications and Services
keywords:
  - sso
  - idm
  - openid connect
  - saml
  - kerberos
  - ldap
home: https://www.keycloak.org/
icon: https://www.keycloak.org/resources/images/keycloak_icon_512px.svg
sources:
  - https://github.com/codecentric/helm-charts
  - https://github.com/jboss-dockerfiles/keycloak
  - https://github.com/bitnami/charts/tree/master/bitnami/postgresql
  - https://github.com/ethdevops/helm-charts
maintainers:
  - name: unguiculus
    email: unguiculus@gmail.com
  - name: thomasdarimont
    email: thomas.darimont+github@gmail.com
  - name: elasticroentgen
    email: markus@ethereum.org
dependencies:
  - name: postgresql
    version: "1.1.3"
    repository: https://ethdevops.github.io/helm-charts
    condition: postgresql.enabled
