apiVersion: v2
name: outline
description: OpenSource alternative for Notion
type: application

version: 0.1.0

# App metadata
appVersion: "1.0.0"
maintainers:
  - name: elasticroentgen
    email: markus.keil@ethereum.org
dependencies:
- name: postgresql
  #version: ">0.0.0-0"
  #repository: file://../postgresql
  version: "1.1.3"
  repository: https://ethdevops.github.io/helm-charts
  condition: postgresql.enabled
- name: redis
  #version: ">0.0.0-0"
  #repository: file://../redis
  version: "1.0.3"
  repository: https://ethdevops.github.io/helm-charts
  condition: redis.enabled
