apiVersion: v1
kind: Service
metadata:
  name: fulltext
  labels:
    {{- include "huly.componentLabels" (dict "component" "fulltext" "root" .) | nindent 4 }}
    app: fulltext
  {{- include "huly.serviceAnnotations" (dict "cfg" .Values.fulltext.service "root" .) | nindent 2 }}
spec:
  {{- include "huly.serviceSpec" (dict "cfg" .Values.fulltext.service "root" .) | nindent 2 }}
  selector:
    app: fulltext
  ports:
    - name: http
      port: 4700
      targetPort: 4700
      {{- include "huly.servicePortNodePort" .Values.fulltext.service | nindent 6 }}
