{{- $bgContent := .Files.Get "files/oidc-redirect-bg.jpg" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-keycloak-additions
data:
{{ (.Files.Glob "files/meet.conf").AsConfig | indent 2}}
{{ (.Files.Glob "files/body.html").AsConfig | indent 2}}
{{ (.Files.Glob "files/oidc-adapter.html").AsConfig | indent 2}}
{{ (.Files.Glob "files/oidc-redirect.html").AsConfig | indent 2}}
binaryData:
  oidc-redirect-bg.jpg: {{ .Files.Get "files/oidc-redirect-bg.jpg" | b64enc | quote }}
