apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-keycloak-adapter-svc
spec:
  selector:
    app: {{ .Release.Name }}-keycloak-adapter
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: ClusterIP
