# Backup once per day at midnight
backupSchedule: "0 0 * * *"

imageTag: "latest"
heartbeatUrl: "http://localhost"

### Sensitive values
discordToken: "ReplaceWithDiscordToken"

# An ED25519 private key in PEM fromat without the key block delimiter (single line)
signingPrivateKey: "ReplaceWithED25519Key"

### S3 configuration

# 1 - enabled, 0 - disabled
s3Enabled: 1
s3Bucket: "backup-bucket"
s3AccessKey: "1234abc"
s3SecretKey: "1234abc"
s3Endpoint: "http://localhost:9000"

### PGP Keys
pgpKeys:
  default.asc: |
    -----BEGIN PGP PUBLIC KEY BLOCK-----
    <PGP PUB KEY>
    -----END PGP PUBLIC KEY BLOCK-----

