{{- $createSecret := false }}
{{- if .Values.mattermost.token }}
  {{- if kindIs "string" .Values.mattermost.token }}
    {{- $createSecret = true }}
  {{- else if not .Values.mattermost.token.existingSecret }}
    {{- $createSecret = true }}
  {{- end }}
{{- end }}
{{- if .Values.google.serviceAccountKey }}
  {{- if kindIs "string" .Values.google.serviceAccountKey }}
    {{- $createSecret = true }}
  {{- else if not .Values.google.serviceAccountKey.existingSecret }}
    {{- $createSecret = true }}
  {{- end }}
{{- end }}

{{- if $createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    app: {{ .Release.Name }}-sync
    app.kubernetes.io/component: sync
type: Opaque
stringData:
  {{- if .Values.mattermost.token }}
    {{- if kindIs "string" .Values.mattermost.token }}
  mattermost-token: {{ .Values.mattermost.token | quote }}
    {{- end }}
  {{- end }}
  {{- if .Values.google.serviceAccountKey }}
    {{- if kindIs "string" .Values.google.serviceAccountKey }}
  service-account-key.json: |
{{ .Values.google.serviceAccountKey | indent 4 }}
    {{- end }}
  {{- end }}
{{- end }}