{{- if or (and (not .Values.mattermost.existingSecret) .Values.mattermost.token) (and (not .Values.google.existingSecret) .Values.google.serviceAccountKey) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    app: {{ .Release.Name }}-sync
    app.kubernetes.io/component: sync
type: Opaque
stringData:
  {{- if and (not .Values.mattermost.existingSecret) .Values.mattermost.token }}
  mattermost-token: {{ .Values.mattermost.token | quote }}
  {{- end }}
  {{- if and (not .Values.google.existingSecret) .Values.google.serviceAccountKey }}
  service-account-key.json: |
{{ .Values.google.serviceAccountKey | indent 4 }}
  {{- end }}
{{- end }}