image:
  repository: docker.ethquokkaops.io/ethquokkaops/ethdevops/jitsi-monitor-docker
  tag: v0.1.4
  pullPolicy: IfNotPresent
config:
  jitsiUrl: "https://jitsihost"
  bridgeRegions: "au,eu,us"
  runtime: "60"
  mediaOption: "1"
  takeScreenshots: "false"

# Service configuration
service:
  type: ClusterIP
  port: 8000

podAnnotations: {}