image:
  repository: docker.ethquokkaops.io/ethquokkaops/ethdevops/jitsi-monitor-docker
  tag: latest
  pullPolicy: IfNotPresent
config:
  jitsiUrl: "https://jitsihost"
  bridgeRegions: "au,eu,us"
  runtime: "60"
  mediaOption: "1"
  takeScreenshots: "false"
cronJob:
  schedule: "15 * * * *"

# Service configuration
service:
  type: ClusterIP
  port: 8000
  annotations: {}