apiVersion: v2
name: quokka-service-registry
description: A Helm chart for QuokkaServiceRegistry - A comprehensive service catalog management application
type: application
iversion: 0.2.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: "1.1.3"
    repository: https://ethdevops.github.io/helm-charts
    condition: postgresql.enabled

keywords:
  - service-registry
  - catalog
  - dotnet
  - aspnet

maintainers:
  - name: QuokkaServiceRegistry Team
