replicaCount: 1

image:
  repository: quokka-service-registry
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 80
  targetPort: http
  annotations: {}

ingress:
  enabled: false

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  periodSeconds: 30

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}

secrets:
  auth:
    existingSecret: ""
    secretKeys:
      googleClientId: "google-client-id"
      googleClientSecret: "google-client-secret"
      authorizedUsers: "authorized-users"
      localAdminUsername: "local-admin-username"
      localAdminPassword: "local-admin-password"
  
  database:
    existingSecret: ""
    secretKeys:
      username: "username"
      password: "password"

config:
  allowLocalAdminBypass: true
  allowedHosts: "*"
  logging:
    logLevel:
      default: "Information"
      microsoftAspNetCore: "Warning"

postgresql:
  enabled: true
  auth:
    existingSecret: ""
    secretKeys:
      adminPasswordKey: "postgres-password"
      userPasswordKey: "password"
    username: "quokka"
    database: "quokka_service_registry"
  primary:
    persistence:
      enabled: true
      size: 8Gi