apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-github-autoscaler-ui
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-github-autoscaler-ui
    ethquokkaops.io/expose-to-teleport: "true"
    ethquokkaops.io/allow-ef-org: "true"
  {{- with .Values.frontendService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.frontendService.type }}
  selector:
    app: {{ .Release.Name }}-github-autoscaler-ui
  ports:
    - name: http
      port: 80
