apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-github-autoscaler-ui
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-github-autoscaler-ui
    ethquokkaops.io/expose-to-teleport: true
  annotations:
    teleport.dev/name: github-runners
spec:
  selector:
    app: {{ .Release.Name }}-github-autoscaler-ui
  ports:
    - name: http
      port: 80
