apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-github-autoscaler
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-github-autoscaler
spec:
  selector:
    app: {{ .Release.Name }}-github-autoscaler
  ports:
    - name: http
      port: 5178
    - name: metrics
      port: 9000
