apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "discourse.fullname" . }}-config
  labels:
    {{- include "discourse.labels" . | nindent 4 }}
data:
  RUBY_GC_HEAP_GROWTH_MAX_SLOTS: "40000"
  DISCOURSE_HOSTNAME: "{{ .Values.forum.hostname }}"
  LANG: "en_US.UTF-8"
  UNICORN_WORKERS: "{{ .Values.forum.workers }}"
  DISCOURSE_FORCE_HTTPS: "true"
  LETSENCRYPT_ACCOUNT_EMAIL: "{{ .Values.forum.letsencrypt.email }}"
  DOCKER_HOST_IP: "172.17.0.1"
  RAILS_ENV: "production"
  UNICORN_SIDEKIQS: "1"
  DISCOURSE_DB_HOST: ""
  DISCOURSE_DB_PORT: ""
  DISCOURSE_SMTP_ADDRESS: "{{ .Values.forum.mail.host }}"
  DISCOURSE_SMTP_PORT: "{{ .Values.forum.mail.port }}"
  RUBY_GC_HEAP_INIT_SLOTS: "400000"
  RUBY_GC_HEAP_OLDOBJECT_LIMIT_FACTOR: "1.5"
  DISCOURSE_DB_SOCKET: "/var/run/postgresql"
  LETSENCRYPT_DIR: "/shared/letsencrypt"
  DISCOURSE_DEVELOPER_EMAILS: {{ join ","" .Values.forum.admins | quote }}
  PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  RUBY_VERSION: "3.3.6"
  PG_MAJOR: "15"
  RUBY_ALLOCATOR: "/usr/lib/libjemalloc.so"
  LEFTHOOK: "0"
  DEBIAN_RELEASE: "bookworm"
  LC_ALL: "en_US.UTF-8"
  LANGUAGE: "en_US.UTF-8"
