{{- if not .Values.forum.mail.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "discourse.fullname" . }}-smtp
  labels:
    {{- include "discourse.labels" . | nindent 4 }}
type: Opaque
data:
  DISCOURSE_SMTP_USER_NAME: {{ .Values.forum.mail.user | b64enc | quote }}
  DISCOURSE_SMTP_PASSWORD: {{ .Values.forum.mail.password | b64enc | quote }}
{{- end }}