apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "discourse.fullname" . }}
  labels:
    {{- include "discourse.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "discourse.fullname" . }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "discourse.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "discourse.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "discourse.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}/{{ .Values.forum.name }}:{{ .Values.forum.version | default .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: discourse-shared
              mountPath: /shared
            - name: discourse-logs
              mountPath: /var/log
            {{- end }}
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: discourse-shared
        labels:
          {{- include "discourse.labels" . | nindent 10 }}
          component: shared-storage
      spec:
        accessModes:
          - {{ .Values.persistence.shared.accessMode }}
        {{- if .Values.persistence.shared.storageClass }}
        storageClassName: {{ .Values.persistence.shared.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.shared.size }}
    - metadata:
        name: discourse-logs
        labels:
          {{- include "discourse.labels" . | nindent 10 }}
          component: logs-storage
      spec:
        accessModes:
          - {{ .Values.persistence.logs.accessMode }}
        {{- if .Values.persistence.logs.storageClass }}
        storageClassName: {{ .Values.persistence.logs.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.logs.size }}
  {{- end }}
