{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "postgresql.fullname" . }}-netpol
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "postgresql.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  {{- if .Values.networkPolicy.allowedPods }}
  - from:
    {{- range .Values.networkPolicy.allowedPods }}
    - podSelector:
        matchLabels:
          {{- toYaml . | nindent 10 }}
    {{- end }}
    ports:
    - protocol: TCP
      port: 5432
  {{- end }}
  {{- if .Values.networkPolicy.allowedNamespaces }}
  - from:
    {{- range .Values.networkPolicy.allowedNamespaces }}
    - namespaceSelector:
        matchLabels:
          {{- toYaml . | nindent 10 }}
    {{- end }}
    ports:
    - protocol: TCP
      port: 5432
  {{- end }}
  egress:
  - {} # Allow all outbound traffic for DNS resolution and other essential services
{{- end }}