{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.fullname" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
    app.kubernetes.io/component: primary
type: Opaque
data:
  {{- if .Values.auth.postgresPassword }}
  postgres-password: {{ .Values.auth.postgresPassword | b64enc | quote }}
  {{- else }}
  postgres-password: {{ printf "%s-%s-postgresql" .Release.Name .Release.Namespace | sha256sum | trunc 16 | b64enc | quote }}
  {{- end }}
  {{- if .Values.auth.password }}
  password: {{ .Values.auth.password | b64enc | quote }}
  {{- end }}
{{- end }}