apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql.fullname" . }}-headless
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
    app.kubernetes.io/component: primary
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: tcp-postgresql
      port: {{ .Values.service.ports.postgresql }}
      targetPort: tcp-postgresql
      protocol: TCP
  selector:
    {{- include "postgresql.selectorLabels" . | nindent 4 }}
