apiVersion: v2
name: patchman
description: A Helm chart for patchman
type: application

version: 0.0.4

# App metadata
appVersion: "1.0.0"
maintainers:
  - name: elasticroentgen
    email: markus.keil@ethereum.org
