baseDomain: patchman.example.com
image:
  repository: docker.ethquokkaops.io/ethquokkaops/ethdevops/patchman-docker
  tag: main
commonAnnotations: {}
podAnnotations: {}
extraInitContainers: {}
resources: {}
  # limits:
  #   cpu: 500m
  #   memory: 512Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
ingress:
  enabled: false
  className: ""
  annotations: {}
  tls:
    secretName: ""
