apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jitsi-meet.jibri.fullname" . }}-cont-inits
  labels:
    {{- include "jitsi-meet.jibri.labels" . | nindent 4 }}
data:
  10-config: |
    {{- if .Values.jibri.custom.contInit._10_config }}
      {{- .Values.jibri.custom.contInit._10_config | nindent 4 }}
    {{- else }}
    # Using jibri /etc/cont-init.d/10-config from container image
    {{ end }}

