apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-config
  labels:
    {{- include "frag-jetzt.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
      listen 80;
      server_name _;

      root /var/www/frag.jetzt;
      index index.csr.html;

      gzip on;
      gzip_types application/javascript application/json text/css image/svg+xml;

      location /api {
        proxy_pass http://{{ include "frag-jetzt.backend.fullname" . }}:{{ .Values.backend.port }};
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }

      location /gateway-api {
        proxy_pass http://{{ include "frag-jetzt.ws-gateway.fullname" . }}:{{ .Values.wsGateway.port }};
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }

      location /gateway/ws/websocket {
        proxy_pass http://{{ include "frag-jetzt.ws-gateway.fullname" . }}:{{ .Values.wsGateway.port }};
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }

      location / {
        try_files $uri $uri/ /index.html;
      }
    }
