{{- if .Values.aiProvider.enabled }}
{{- $aiPg := index .Subcharts "ai-postgresql" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ai-provider
  labels:
    {{- include "frag-jetzt.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Release.Name }}-ai-provider
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-ai-provider
    spec:
      initContainers:
        - name: init-ai-db
          image: {{ (index .Values "ai-postgresql").image.registry | default "" }}{{ ternary "/" "" (not (empty ((index .Values "ai-postgresql").image.registry | default ""))) }}postgres:{{ (index .Values "ai-postgresql").image.tag }}
          command: ["/bin/bash", "/scripts/init-replication.sh"]
          volumeMounts:
            - name: init-script
              mountPath: /scripts
      containers:
        - name: ai-provider
          image: {{ .Values.aiProvider.image.repository }}:{{ .Values.aiProvider.image.tag }}
          imagePullPolicy: {{ .Values.aiProvider.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.aiProvider.port }}
          env:
            - name: ORIGINS
              value: {{ .Values.aiProvider.origins | default (include "frag-jetzt.serverRootUrl" .) | quote }}
            - name: SECRET_KEY
              value: {{ .Values.aiProvider.secretKey | quote }}
            - name: SECRET_ALGORITHM
              value: {{ .Values.aiProvider.secretAlgorithm | quote }}
            - name: ROOT_PATH
              value: "/ai"
            - name: POSTGRES_HOST
              value: {{ include "postgresql.v1.primary.fullname" $aiPg | quote }}
            - name: POSTGRES_PORT
              value: {{ include "postgresql.v1.service.port" $aiPg | quote }}
            - name: POSTGRES_USER
              value: {{ include "postgresql.v1.username" $aiPg | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ (index .Values "ai-postgresql").auth.password | quote }}
            - name: POSTGRES_DB
              value: {{ include "postgresql.v1.database" $aiPg | quote }}
            - name: CHROMA_HOST
              value: {{ .Release.Name }}-ai-chroma
            - name: CHROMA_PORT
              value: "8000"
            - name: CHROMA_SERVER_AUTH_CREDENTIALS
              value: {{ .Values.aiProvider.chroma.auth.token | quote }}
          resources: {}
      volumes:
        - name: init-script
          configMap:
            name: {{ .Release.Name }}-ai-pg-init
            defaultMode: 0755
{{- end }}
