apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frag-jetzt.rabbitmq.fullname" . }}
  labels:
    {{- include "frag-jetzt.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ include "frag-jetzt.rabbitmq.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "frag-jetzt.rabbitmq.fullname" . }}
    spec:
      containers:
        - name: rabbitmq
          image: {{ .Values.rabbitmq.image.repository }}:{{ .Values.rabbitmq.image.tag }}
          imagePullPolicy: {{ .Values.rabbitmq.image.pullPolicy }}
          ports:
            - name: amqp
              containerPort: 5672
            - name: stomp
              containerPort: 61613
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: {{ .Values.rabbitmq.auth.username | quote }}
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "frag-jetzt.secretName" . }}
                  key: {{ .Values.rabbitmq.auth.existingSecret.passwordKey | default "rabbitmq-password" }}
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
            - name: rabbitmq-plugins
              mountPath: /etc/rabbitmq/enabled_plugins
              subPath: enabled_plugins
              readOnly: true
          resources: {}
      volumes:
        - name: rabbitmq-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-rabbitmq-pvc
        - name: rabbitmq-plugins
          configMap:
            name: {{ .Release.Name }}-rabbitmq-plugins
