{{- if .Values.aiProvider.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-ai-postgres-pvc
  labels:
    {{- include "frag-jetzt.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.aiProvider.postgres.persistence.size }}
{{- end }}
