{{- if not .Values.auth.existingSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-frag-jetzt-secret
  labels:
    {{- include "frag-jetzt.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.auth.jwtSecret | quote }}
  {{- if .Values.rabbitmq.auth.password }}
  rabbitmq-password: {{ .Values.rabbitmq.auth.password | quote }}
  {{- end }}
  {{- if .Values.keycloak.eventPassword }}
  keycloak-event-password: {{ .Values.keycloak.eventPassword | quote }}
  {{- end }}
  {{- if and .Values.vapid.enabled .Values.vapid.publicKey }}
  vapid-public-key: {{ .Values.vapid.publicKey | quote }}
  vapid-private-key: {{ .Values.vapid.privateKey | quote }}
  {{- end }}
{{- end }}
