apiVersion: v1
kind: Service
metadata:
  name: {{ include "frag-jetzt.ws-gateway.fullname" . }}
  labels:
    {{- include "frag-jetzt.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.wsGateway.port }}
      targetPort: {{ .Values.wsGateway.port }}
  selector:
    app: {{ include "frag-jetzt.ws-gateway.fullname" . }}
