apiVersion: v1
kind: Service
metadata:
  name: {{ include "frag-jetzt.frontend.fullname" . }}
  labels:
    {{- include "frag-jetzt.labels" . | nindent 4 }}
  {{- with .Values.frontend.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.frontend.service.type | default "ClusterIP" }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port | default 80 }}
      targetPort: 80
      {{- if and (eq .Values.frontend.service.type "NodePort") .Values.frontend.service.nodePort }}
      nodePort: {{ .Values.frontend.service.nodePort }}
      {{- end }}
  selector:
    app: {{ include "frag-jetzt.frontend.fullname" . }}
