{{- if .Values.aiProvider.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ai-postgres
  labels:
    {{- include "frag-jetzt.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    app: {{ .Release.Name }}-ai-postgres
{{- end }}
