{{- if .Values.aiProvider.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ai-chroma
  labels:
    {{- include "frag-jetzt.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    app: {{ .Release.Name }}-ai-chroma
{{- end }}
