apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wazuh.fullname" . }}-manager-config
data:
  script.sh: |-
    #/bin/sh
    # Updates each workers config to fix hostname
    cp /ossec.conf /wazuh-config-mount/etc/ossec.conf
    node_index=${HOSTNAME##*-}
    sed -i "s/___INDEX___/$node_index/g" /wazuh-config-mount/etc/ossec.conf
  master.conf: |
    {{- tpl .Values.wazuh.master.conf . | indent 2 }}
  worker.conf: |
    {{- tpl .Values.wazuh.worker.conf . | indent 2 }}