{{- if not .Values.wazuh.apiCred.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: wazuh-api-cred
data:
  username: {{ .Values.wazuh.apiCred.username | default (randAlphaNum 10) | b64enc }}
  password: {{ .Values.wazuh.apiCred.password | default (randAlphaNum 16) | b64enc }}
{{- end }}
