{{- if not .Values.wazuh.authd.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: wazuh-authd-pass
data:
  authd.pass: {{ .Values.wazuh.authd.pass | default (randAlphaNum 16) | b64enc }}
{{- end }}