apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    {{- if .Values.service.teleport.enabled }}
    ethquokkaops.io/expose-to-teleport: "true"
    {{- if .Values.service.teleport.allowEfOrg }}
    ethquokkaops.io/allow-ef-org: "true"
    {{- end }}
    {{- end }}
  {{- if .Values.service.teleport.enabled }}
  annotations:
    teleport.dev/name: {{ .Values.service.teleport.name }}
  {{- end }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http
