apiVersion: v1
kind: Secret
metadata:
  name: {{ include "safe-infrastructure.fullname" . }}-credentials
  labels:
    {{- include "safe-infrastructure.labels" . | nindent 4 }}
type: Opaque
data:
  # Database credentials
  postgres-password: {{ .Values.credentials.postgres.password | b64enc | quote }}
  postgres-user: {{ .Values.credentials.postgres.user | b64enc | quote }}
  postgres-database: {{ .Values.credentials.postgres.database | b64enc | quote }}
  
  # Application secrets
  django-secret-key: {{ .Values.credentials.django.secretKey | b64enc | quote }}
  cfg-secret-key: {{ .Values.credentials.cfg.secretKey | b64enc | quote }}
  
  # Auth tokens
  cgw-auth-token: {{ .Values.credentials.cgw.authToken | b64enc | quote }}
  
  # JWT secrets
  jwt-issuer: {{ .Values.credentials.jwt.issuer | b64enc | quote }}
  jwt-secret: {{ .Values.credentials.jwt.secret | b64enc | quote }}
  
  # Events service credentials
  events-admin-email: {{ .Values.credentials.events.adminEmail | b64enc | quote }}
  events-admin-password: {{ .Values.credentials.events.adminPassword | b64enc | quote }}
  
  # Django superuser credentials
  django-superuser-username: {{ .Values.credentials.django.superuser.username | b64enc | quote }}
  django-superuser-password: {{ .Values.credentials.django.superuser.password | b64enc | quote }}
  django-superuser-email: {{ .Values.credentials.django.superuser.email | b64enc | quote }}
  
  # Encryption keys
  fingerprint-encryption-key: {{ .Values.credentials.cgw.fingerprintEncryptionKey | b64enc | quote }}