apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-hc-config
data:
  ALLOWED_HOSTS: {{ .Values.baseDomain }}
  APPRISE_ENABLED: "False"
  DB: postgres
  DB_CONN_MAX_AGE: "0"
  DB_HOST: {{ .Release.Name }}-hc-db
  DB_NAME: {{ .Values.db.name }}
  DB_PORT: "5432"
  DB_SSLMODE: prefer
  DB_TARGET_SESSION_ATTRS: read-write
  DB_USER: {{ .Values.db.user }}
  DEBUG: "{{ .Values.debugEnabled }}"
  DEFAULT_FROM_EMAIL: healthchecks@{{ .Values.baseDomain }}
  DISCORD_CLIENT_ID: "{{ .Values.discord.clientId }}"
  EMAIL_HOST: "{{ .Values.email.host }}"
  EMAIL_HOST_USER: "{{ .Values.email.user }}"
  EMAIL_PORT: "587"
  EMAIL_USE_TLS: "True"
  EMAIL_USE_VERIFICATION: "True"
  INTEGRATIONS_ALLOW_PRIVATE_IPS: "False"
  LINENOTIFY_CLIENT_ID: ""
  LINENOTIFY_CLIENT_SECRET: ""
  MASTER_BADGE_LABEL: "{{ .Values.siteName }}"
  MATRIX_ACCESS_TOKEN: ""
  MATRIX_HOMESERVER: ""
  MATRIX_USER_ID: ""
  MATTERMOST_ENABLED: "True"
  MSTEAMS_ENABLED: "True"
  OPSGENIE_ENABLED: "True"
  PAGERTREE_ENABLED: "True"
  PD_APP_ID: ""
  PD_ENABLED: "True"
  PING_BODY_LIMIT: "10000"
  PING_EMAIL_DOMAIN: localhost
  PING_ENDPOINT: http://localhost:8000/ping/
  PROMETHEUS_ENABLED: "True"
  PUSHBULLET_CLIENT_ID: ""
  PUSHBULLET_CLIENT_SECRET: ""
  PUSHOVER_API_TOKEN: ""
  PUSHOVER_EMERGENCY_EXPIRATION: "86400"
  PUSHOVER_EMERGENCY_RETRY_DELAY: "300"
  PUSHOVER_SUBSCRIPTION_URL: ""
  REGISTRATION_OPEN: "{{ .Values.registrationEnabled }}"
  REMOTE_USER_HEADER: ""
  ROCKETCHAT_ENABLED: "True"
  RP_ID: ""
  S3_ACCESS_KEY: ""
  S3_BUCKET: ""
  S3_ENDPOINT: ""
  S3_REGION: ""
  S3_SECRET_KEY: ""
  S3_TIMEOUT: "60"
  S3_SECURE: "True"
  SHELL_ENABLED: "False"
  SIGNAL_CLI_SOCKET: ""
  SITE_LOGO_URL: ""
  SITE_NAME: "{{ .Values.siteName }}"
  SITE_ROOT: http://{{ .Values.baseDomain }}
  SLACK_CLIENT_ID: ""
  SLACK_CLIENT_SECRET: ""
  SLACK_ENABLED: "True"
  # SMTPD_PORT: ""
  SPIKE_ENABLED: "True"
  TELEGRAM_BOT_NAME: ExampleBot
  TELEGRAM_TOKEN: ""
  TRELLO_APP_KEY: ""
  TWILIO_ACCOUNT: ""
  TWILIO_AUTH: ""
  TWILIO_FROM: ""
  TWILIO_USE_WHATSAPP: "False"
  USE_PAYMENTS: "False"
  VICTOROPS_ENABLED: "True"
  WEBHOOKS_ENABLED: "True"
  ZULIP_ENABLED: "True"

