apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-hc-db
  labels:
    app: {{ .Release.Name }}-hc-db
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-hc-db
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-hc-db
    spec:
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-hc-db-data
      containers:
      - name: db
        image: postgres:16
        env:
          - name: POSTGRES_DB
            value: {{ .Values.db.name }}
          - name: POSTGRES_USER
            value: {{ .Values.db.user }}
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-hc-secrets
                key: DB_PASSWORD
        volumeMounts:
          - name: db-data
            mountPath: /var/lib/postgresql/data
            subPath: pg
        ports:
          - containerPort: 5432
        readinessProbe:
          tcpSocket:
            port: 5432
          periodSeconds: 5
          initialDelaySeconds: 10
          failureThreshold: 3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-hc-db-data
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi

