apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-db
  labels:
    app: {{ .Release.Name }}-db
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-db
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-db
    spec:
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-db-data
      containers:
      - name: db
        image: postgres:12
        env:
          - name: POSTGRES_DB
            value: {{ .Values.db.name }}
          - name: POSTGRES_PASSWORD
            value: {{ .Values.db.password }}
        volumeMounts:
          - name: db-data
            mountPath: /var/lib/postgresql/data
        ports:
          - db: 5432
        readinessProbe:
          tcpSocket:
            port: 5432
          periodSeconds: 5
          initialDelaySeconds: 10
          failureThreshold: 3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-db-data
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi

