{{- if not .Values.useExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-hc-secrets
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.db.password }}
  DISCORD_CLIENT_SECRET: "{{ .Values.discord.clientSecret }}"
  EMAIL_HOST_PASSWORD: "{{ .Values.email.password }}"
  SECRET_KEY: "{{ .Values.secretKey }}"
{{- end }}
