{{- if .Values.gateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vexa.componentName" (list . "gateway") }}
  labels:
    {{- include "vexa.labels" . | nindent 4 }}
    {{- with .Values.gateway.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.gateway.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.gateway.service.type }}
  {{- with .Values.gateway.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.gateway.service.port }}
      targetPort: http
      {{- if .Values.gateway.service.nodePort }}
      nodePort: {{ .Values.gateway.service.nodePort }}
      {{- end }}
  selector:
    {{- include "vexa.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
{{- end }}
