{{- if not .Values.indexer.cred.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: indexer-cred
data:
  username: {{ .Values.indexer.cred.username | default (randAlphaNum 10) | b64enc }}
  password: {{ .Values.indexer.cred.password | default (randAlphaNum 16) | b64enc }}
{{- end }}