apiVersion: v1
kind: Service
metadata:
  name: {{ include "wazuh.fullname" . }}-indexer-nodes
  labels:
    app: {{ include "wazuh.fullname" . }}-indexer
  annotations:
    {{- toYaml .Values.indexer.service.annotations | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: indexer-nodes
      port: {{ .Values.indexer.service.nodes }}
      targetPort: {{ .Values.indexer.service.nodes }}
  selector:
    app: {{ include "wazuh.fullname" . }}-indexer
