{{- if and .Values.networkPolicy.enabled .Values.database.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "domainmod.db.fullname" . }}
  labels:
    {{- include "domainmod.db.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "domainmod.db.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  {{- with .Values.networkPolicy.db.ingress }}
  ingress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.networkPolicy.db.egress }}
  egress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
