{{- if .Values.externalSecrets.enabled }}
{{- if .Values.externalSecrets.ceph.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.ceph.secretName | default (printf "%s-ceph-config" (include "k8s-ceph-backup.fullname" .)) }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "k8s-ceph-backup.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.ceph.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: {{ .Values.externalSecrets.secretStore.kind | default "SecretStore" }}
  target:
    name: {{ .Values.externalSecrets.ceph.secretName | default (printf "%s-ceph-config" (include "k8s-ceph-backup.fullname" .)) }}
    creationPolicy: Owner
  data:
  - secretKey: ceph.conf
    remoteRef:
      key: {{ .Values.externalSecrets.ceph.keys.cephConf.key }}
      {{- if .Values.externalSecrets.ceph.keys.cephConf.property }}
      property: {{ .Values.externalSecrets.ceph.keys.cephConf.property }}
      {{- end }}
  - secretKey: keyring
    remoteRef:
      key: {{ .Values.externalSecrets.ceph.keys.keyring.key }}
      {{- if .Values.externalSecrets.ceph.keys.keyring.property }}
      property: {{ .Values.externalSecrets.ceph.keys.keyring.property }}
      {{- end }}
{{- end }}

{{- if .Values.externalSecrets.gpg.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.gpg.secretName | default (printf "%s-gpg-keys" (include "k8s-ceph-backup.fullname" .)) }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "k8s-ceph-backup.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.gpg.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: {{ .Values.externalSecrets.secretStore.kind | default "SecretStore" }}
  target:
    name: {{ .Values.externalSecrets.gpg.secretName | default (printf "%s-gpg-keys" (include "k8s-ceph-backup.fullname" .)) }}
    creationPolicy: Owner
  data:
  - secretKey: pubkey.asc
    remoteRef:
      key: {{ .Values.externalSecrets.gpg.keys.pubkey.key }}
      {{- if .Values.externalSecrets.gpg.keys.pubkey.property }}
      property: {{ .Values.externalSecrets.gpg.keys.pubkey.property }}
      {{- end }}
  {{- if .Values.externalSecrets.gpg.keys.trustdb }}
  - secretKey: trustdb.gpg
    remoteRef:
      key: {{ .Values.externalSecrets.gpg.keys.trustdb.key }}
      {{- if .Values.externalSecrets.gpg.keys.trustdb.property }}
      property: {{ .Values.externalSecrets.gpg.keys.trustdb.property }}
      {{- end }}
  {{- end }}
{{- end }}

{{- if .Values.externalSecrets.minio.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.minio.secretName | default (printf "%s-minio-credentials" (include "k8s-ceph-backup.fullname" .)) }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "k8s-ceph-backup.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.minio.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: {{ .Values.externalSecrets.secretStore.kind | default "SecretStore" }}
  target:
    name: {{ .Values.externalSecrets.minio.secretName | default (printf "%s-minio-credentials" (include "k8s-ceph-backup.fullname" .)) }}
    creationPolicy: Owner
  data:
  - secretKey: access-key
    remoteRef:
      key: {{ .Values.externalSecrets.minio.keys.accessKey.key }}
      {{- if .Values.externalSecrets.minio.keys.accessKey.property }}
      property: {{ .Values.externalSecrets.minio.keys.accessKey.property }}
      {{- end }}
  - secretKey: secret-key
    remoteRef:
      key: {{ .Values.externalSecrets.minio.keys.secretKey.key }}
      {{- if .Values.externalSecrets.minio.keys.secretKey.property }}
      property: {{ .Values.externalSecrets.minio.keys.secretKey.property }}
      {{- end }}
{{- end }}
{{- end }}