apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-ceph-backup.serviceAccountName" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "k8s-ceph-backup.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "k8s-ceph-backup.fullname" . }}
  labels:
    {{- include "k8s-ceph-backup.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "k8s-ceph-backup.fullname" . }}
  labels:
    {{- include "k8s-ceph-backup.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "k8s-ceph-backup.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "k8s-ceph-backup.serviceAccountName" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
