{{- if not .Values.secrets.ceph.external }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.ceph.secretName | default (printf "%s-ceph-config" (include "k8s-ceph-backup.fullname" .)) }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "k8s-ceph-backup.labels" . | nindent 4 }}
type: Opaque
data:
  ceph.conf: {{ .Values.secrets.ceph.cephConf | b64enc | quote }}
  keyring: {{ .Values.secrets.ceph.keyring | b64enc | quote }}
{{- end }}

{{- if not .Values.secrets.gpg.external }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.gpg.secretName | default (printf "%s-gpg-keys" (include "k8s-ceph-backup.fullname" .)) }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "k8s-ceph-backup.labels" . | nindent 4 }}
type: Opaque
data:
  pubkey.asc: {{ .Values.secrets.gpg.pubkey | b64enc | quote }}
  {{- if .Values.secrets.gpg.trustdb }}
  trustdb.gpg: {{ .Values.secrets.gpg.trustdb | b64enc | quote }}
  {{- end }}
{{- end }}

{{- if not .Values.secrets.minio.external }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.minio.secretName | default (printf "%s-minio-credentials" (include "k8s-ceph-backup.fullname" .)) }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "k8s-ceph-backup.labels" . | nindent 4 }}
type: Opaque
data:
  access-key: {{ .Values.secrets.minio.accessKey | b64enc | quote }}
  secret-key: {{ .Values.secrets.minio.secretKey | b64enc | quote }}
{{- end }}
