{{- with .Values.appSecret }}
{{- if and .value (not .existingSecret) }}
{{- if lt (len .value) 32 }}
{{- fail "appSecret.value must be at least 32 chars" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "docmost.appSecretName" $ }}
  labels:
    app: {{ $.Release.Name }}-docmost
type: Opaque
data:
  {{ .key }}: {{ .value | b64enc | quote }}
{{- end }}
{{- end }}
