apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-docmost-app
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    app: {{ .Release.Name }}-docmost

