apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jitsi-meet.web.fullname" . }}-defaults
  labels:
    {{- include "jitsi-meet.web.labels" . | nindent 4 }}
data:
  default: |
  {{- if .Values.web.custom.defaults._default }}
    {{- .Values.web.custom.defaults._default | nindent 4 }}
  {{- else }}
  # Using web /defaults/default from container image
  {{ end }}
  ffdhe2048.txt: |
  {{- if .Values.web.custom.defaults._ffdhe2048_txt }}
    {{- .Values.web.custom.defaults._ffdhe2048_txt | nindent 4 }}
  {{- else }}
  # Using web /defaults/ffdhe2048.txt from container image
  {{ end }}
  interface_config.js: |
  {{- if .Values.web.custom.defaults._interface_config_js }}
    {{- .Values.web.custom.defaults._interface_config_js | nindent 4 }}
  {{- else }}
  # Using web /defaults/interface_config.js from container image
  {{ end }}
  meet.conf: |
  {{- if .Values.web.custom.defaults._meet_conf }}
    {{- .Values.web.custom.defaults._meet_conf | nindent 4 }}
  {{- else }}
  # Using web /defaults/meet.conf from container image
  {{ end }}
  nginx.conf: |
  {{- if .Values.web.custom.defaults._nginx_conf }}
    {{- .Values.web.custom.defaults._nginx_conf | nindent 4 }}
  {{- else }}
  # Using web /defaults/nginx.conf from container image
  {{ end }}
{{ (.Files.Glob "files/settings-config.js").AsConfig | indent 2}}
  ssl.conf: |
  {{- if .Values.web.custom.defaults._ssl_conf }}
    {{- .Values.web.custom.defaults._ssl_conf | nindent 4 }}
  {{- else }}
  # Using web /defaults/ssl.conf from container image
  {{ end }}
  system-config.js: |
  {{- if .Values.web.custom.defaults._system_config_js }}
    {{- .Values.web.custom.defaults._system_config_js | nindent 4 }}
  {{- else }}
  # Using web /defaults/system-config.js from container image
  {{ end }}
