{{- if .Values.mariadb.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-hotcrp-mariadb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  {{- with .Values.mariadb.persistence.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.mariadb.persistence.size }}
{{- end }}
