{{- if and .Values.smtp.enabled .Values.smtp.username (not .Values.smtp.existingSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-hotcrp-smtp
type: Opaque
data:
  SMTP_PASSWORD: {{ .Values.smtp.password | b64enc | quote }}
{{- end }}
