apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-hotcrp
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  {{- if and .Values.service.loadBalancerClass (eq .Values.service.type "LoadBalancer") }}
  loadBalancerClass: {{ .Values.service.loadBalancerClass }}
  {{- end }}
  {{- if and .Values.service.externalTrafficPolicy (or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort")) }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  {{- with .Values.service.internalTrafficPolicy }}
  internalTrafficPolicy: {{ . }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.service.port | default 80 }}
      targetPort: http
  selector:
    app: {{ .Release.Name }}-hotcrp
