# Default values for redis.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Redis image configuration
image:
  repository: redis
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

## Redis authentication
auth:
  enabled: false
  # password: ""
  # Use existing secret instead of creating one
  existingSecret: ""
  existingSecretPasswordKey: "redis-password"

## Redis configuration
redis:
  # Custom redis.conf content
  configuration: |
    # Redis configuration file
    bind 0.0.0.0
    port 6379
    tcp-backlog 511
    timeout 0
    tcp-keepalive 300
    
    # Persistence
    save 900 1
    save 300 10
    save 60 10000
    
    stop-writes-on-bgsave-error yes
    rdbcompression yes
    rdbchecksum yes
    dbfilename dump.rdb
    dir /data
    
    # Logging
    loglevel notice
    logfile ""
    
    # Memory management
    maxmemory-policy allkeys-lru
    
    # Slow log
    slowlog-log-slower-than 10000
    slowlog-max-len 128

## Persistence configuration
persistence:
  enabled: true
  # storageClass: ""
  accessModes:
    - ReadWriteOnce
  size: 8Gi

## Service configuration
service:
  type: ClusterIP
  port: 6379
  # nodePort: ""
  # loadBalancerIP: ""

## Bitnami Redis compatibility structure
master:
  service:
    ports:
      redis: 6379

## Service Account
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

## Pod annotations
podAnnotations: {}

## Pod Security Context
podSecurityContext:
  fsGroup: 999

## Security Context
securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 999

## Resource limits and requests
resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

## Liveness probe configuration
livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 5

## Readiness probe configuration
readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 5

## Node selector
nodeSelector: {}

## Tolerations
tolerations: []

## Affinity
affinity: {}