---
apiVersion: v1
kind: ConfigMap
data:
  config.json: |-
    [
      {
        "clusterID": "{{ .Values.clusterId }}",
        "monitors": {{ .Values.monitors | toJson }}{{- if .Values.cephfs.enabled }},
        "cephFS": {
          "subvolumeGroup": "{{ .Values.cephfs.subvolumeGroup }}"
        }{{- end }}
      }
    ]
metadata:
  name: ceph-csi-config
