apiVersion: v1
kind: Service
metadata:
  name: {{ include "postiz.fullname" . }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "postiz.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.service.additionalPorts }}
    {{- toYaml .Values.service.additionalPorts | nindent 4 }}
    {{- end }}
  selector:
    {{- include "postiz.selectorLabels" . | nindent 4 }}
