apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-outline
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-outline
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-outline
    spec:
      initContainers:
        - name: init-config
          image: docker.ethquokkaops.io/dh/alpine:latest
          command: ["/bin/sh", "-c", "chmod 0777 -R /data"]
          volumeMounts:
          - name: outline-storage
            mountPath: /data
      containers:
        - name: outline
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          env:
            - name: PGSSLMODE
              value: disable
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config

            - secretRef:
                name: {{ .Values.existingSecret }}
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: outline-storage
              mountPath: /var/lib/outline/data
      volumes:
        - name: outline-storage
          persistentVolumeClaim:
            claimName: {{.Release.Name}}-outline-pvc

