apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-geoselector-svc
spec:
  selector:
    app: {{ .Release.Name }}-geoselector
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
