apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-web
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-web
    spec:
      containers:
        - name: appflowy-web
          image: {{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: APPFLOWY_BASE_URL
              value: {{ include "appflowy.baseUrl" . | quote }}
            - name: APPFLOWY_GOTRUE_BASE_URL
              value: "{{ include "appflowy.baseUrl" . }}/gotrue"
            - name: APPFLOWY_WS_BASE_URL
              value: {{ include "appflowy.wsUrl" . | quote }}
          {{- with .Values.web.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
