{{- if .Values.podDisruptionBudget.enabled }}
{{- $components := list "admin" "cloud" "gotrue" "web" "worker" -}}
{{- if .Values.ai.enabled }}{{- $components = append $components "ai" }}{{- end }}
{{- if .Values.search.enabled }}{{- $components = append $components "search" }}{{- end }}
{{- range $component := $components }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $.Release.Name }}-{{ $component }}
spec:
  {{- if $.Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ $.Values.podDisruptionBudget.minAvailable }}
  {{- else }}
  maxUnavailable: {{ $.Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ $.Release.Name }}-{{ $component }}
{{- end }}
{{- end }}
