apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gotrue-app
  {{- with .Values.gotrue.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.gotrue.service.type | default "ClusterIP" }}
  ports:
    - name: http
      port: {{ .Values.gotrue.service.port }}
      targetPort: 9999
      {{- if and (eq .Values.gotrue.service.type "NodePort") .Values.gotrue.service.nodePort }}
      nodePort: {{ .Values.gotrue.service.nodePort }}
      {{- end }}
  selector:
    app: {{ .Release.Name }}-gotrue
