apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-admin-app
  {{- with .Values.admin.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.admin.service.type | default "ClusterIP" }}
  ports:
    - name: http
      port: {{ .Values.admin.service.port }}
      targetPort: 3000
      {{- if and (eq .Values.admin.service.type "NodePort") .Values.admin.service.nodePort }}
      nodePort: {{ .Values.admin.service.nodePort }}
      {{- end }}
  selector:
    app: {{ .Release.Name }}-admin
