apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-sync-config
data:
  SOURCE_BUCKET: "{{ .Values.sourceBucket }}"
  SOURCE_ENDPOINT: "{{ .Values.sourceEndpoint }}"
  DESTINATION_BUCKET: "{{ .Values.destinationBucket }}"
  DESTINATION_ENDPOINT: "{{ .Values.destinationEndpoint }}"
  MINIO_EXTRA_ARGS: "{{ .Values.minioExtraArgs }}"
