{{- if .Values.crypt.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-sync-crypt
type: Opaque
stringData:
  CRYPT_PASSWORD: {{ .Values.crypt.password | quote }}
  CRYPT_SALT: {{ required "crypt.salt is required with crypt.password" .Values.crypt.salt | quote }}
{{- end }}
