apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-sync-credentials
type: Opaque
stringData:
  SOURCE_ACCESS_KEY: "{{ .Values.source.accessKey }}"
  SOURCE_SECRET_KEY: "{{ .Values.source.secretKey }}"
  DESTINATION_ACCESS_KEY: "{{ .Values.destination.accessKey }}"
  DESTINATION_SECRET_KEY: "{{ .Values.destination.secretKey }}"
