apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-sync-credentials
type: Opaque
stringData:
  SOURCE_ACCESS_KEY: "{{ .Values.sourceAccessKey }}"
  SOURCE_SECRET_KEY: "{{ .Values.sourceSecretKey }}"
  DESTINATION_ACCESS_KEY: "{{ .Values.destinationAccessKey }}"
  DESTINATION_SECRET_KEY: "{{ .Values.destinationSecretKey }}"
